language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main
